remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Bastion
description: Hardware entropy • Deterministic identities • Air-gap • 1Password

# Repository info for theme
repository: JakeHertenstein/bastion
